# Generated by Django 5.2.14 on 2026-06-14 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('CAMPUS', 'Campus'), ('SPORTS', 'Sports'), ('EVENTS', 'Events'), ('ACADEMICS', 'Academics'), ('LABS', 'Labs')], db_index=True, default='CAMPUS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gallery_new',
                'ordering': ['-created_at'],
            },
        ),
    ]
