# Generated by Django 5.2.14 on 2026-06-14 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_role', models.CharField(choices=[('ALL', 'All'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], db_index=True, default='ALL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notices_new',
                'ordering': ['-created_at'],
            },
        ),
    ]
