# Generated by Django 5.2.14 on 2026-06-14 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, help_text='Department vision statement', null=True)),
                ('mission', models.TextField(blank=True, help_text='Department mission statement', null=True)),
                ('programs_offered', models.TextField(blank=True, help_text='List of programs offered (one per line)', null=True)),
                ('total_seats', models.PositiveIntegerField(default=50)),
                ('established_year', models.PositiveIntegerField(blank=True, help_text='Year the department was established', null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='departments/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments_new',
                'ordering': ['name'],
            },
        ),
    ]
