# Generated by Django 5.2.14 on 2026-06-14 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('event_type', models.CharField(choices=[('NEWS', 'News'), ('EVENT', 'Event'), ('ANNOUNCEMENT', 'Announcement')], db_index=True, default='NEWS', max_length=20)),
                ('body', models.TextField()),
                ('event_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_publish_date', models.DateTimeField(blank=True, db_index=True, help_text='Schedule auto-publish at this datetime', null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='news_events/')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_events_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News / Event',
                'verbose_name_plural': 'News & Events',
                'db_table': 'news_events_new',
                'ordering': ['-created_at'],
            },
        ),
    ]
