# Generated by Django 5.2.14 on 2026-06-14 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('ELIGIBILITY', 'Admission Eligibility'), ('RECOMMENDATION', 'Department Recommendation')], db_index=True, default='ELIGIBILITY', max_length=30)),
                ('input_json', models.JSONField()),
                ('output_json', models.JSONField()),
                ('model_used', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('confidence_score', models.FloatField(default=0.85)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='students.student')),
            ],
            options={
                'db_table': 'ai_predictions_new',
                'ordering': ['-created_at'],
            },
        ),
    ]
